with-expecter: true
filename: "mock_{{.InterfaceName}}.go"
mockname: "Mock{{.InterfaceName}}"
outpkg: mockery
packages:
  mocks/internal/core/services:
    interfaces:
      Store:
        config:
          dir: "{{.InterfaceDir}}/internal/mockery"
      Foobar:
        config:
          dir: "{{.InterfaceDir}}/internal/mockery"
